name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: windows-2025-vs2026
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Setup mise
        uses: jdx/mise-action@v4

      - name: Show tool versions
        run: |
          cmake --version
          clang-format --version

      - name: Config
        run: cmake --preset ninja

      - name: Build
        run: cmake --build --preset ninja

      - name: Test
        run: ctest --preset ninja --output-on-failure

      - name: Check format
        run: mise run format-check
