name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: Check (${{ matrix.preset }})
    strategy:
      fail-fast: false
      matrix:
        preset:
          - vs
          - ninja-msvc
          - ninja-clang-cl

    runs-on: windows-2025-vs2026
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Setup mise
        uses: jdx/mise-action@v4

      - name: Configure MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Show tool versions
        run: |
          cmake --version
          clang-format --version

      - name: Config
        run: cmake --preset ${{ matrix.preset }}

      - name: Build
        run: cmake --build --preset ${{ matrix.preset }}

      - name: Test
        run: ctest --preset ${{ matrix.preset }} --output-on-failure

      - name: Check format
        run: mise run format-check
